# Generated by Django 5.0.4 on 2024-04-28 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URL',
            fields=[
                ('shortURL', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('longURL', models.CharField(max_length=50)),
            ],
        ),
    ]
